# nordless theme
[colors.primary]
background = "#2E3440" # emacs(bg)
foreground = "#D8DEE9" # emacs(fg)
dim_foreground = "#A5ABB6" # ????

[colors.cursor]
cursor = "#BF616A" # emacs(red)
text = "#2E3440" # emacs(bg)

[colors.normal]
black = "#3B4252" # emacs(bg+)
blue = "#81A1C1" # emacs(blue)
cyan = "#88C0D0" # emacs(docs)
green = "#A3BE8C" # emacs(green)
magenta = "#B48EAD" # ????
red = "#BF616A" # emacs(red)
white = "#E5E9F0" # emacs(fg+)
yellow = "#EBCB8B" # emacs(yellow)

[colors.bright]
black = "#4C566A" # emacs(fade)
blue = "#81A1C1" # emacs(blue)
cyan = "#8FBCBB" # ????
green = "#A3BE8C" # emacs(green)
magenta = "#B48EAD" # ????
red = "#BF616A" # emacs(red)
white = "#ECEFF4" # ????
yellow = "#EBCB8B" # emacs(yellow)

[colors.dim]
black = "#373E4D" # ????
blue = "#68809A" # ????
cyan = "#6D96A5" # ????
green = "#809575" # ????
magenta = "#8C738C" # ????
red = "#94545D" # ????
white = "#AEB3BB" # ????
yellow = "#B29E75" # ????

# [colors.search.footer_bar]
# background = "#434c5e"
# foreground = "#d8dee9"

[colors.search.matches]
background = "#88C0D0" # emacs(docs)
foreground = "CellBackground"

[colors.selection]
background = "#4C566A" # emacs(fade)
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#D8DEE9" # emacs(fg)
text = "#2E3440" # emacs(bg)
