[general]
live_config_reload = true
import = [
  "~/Documents/dotfiles/alacritty/keys.toml",
  "~/Documents/dotfiles/alacritty/ui.toml",
  "~/Documents/dotfiles/alacritty/kaoless-theme.toml",
]

[debug]
print_events = true
render_timer = false

[env]
TERM = "alacritty-direct"
