#!/usr/bin/env bash

# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# config
yabai -m config layout bsp

yabai -m config top_padding    4
yabai -m config bottom_padding 4
yabai -m config left_padding   4
yabai -m config right_padding  4
yabai -m config window_gap     4

yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off

# (tr)additional
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on
yabai -m config window_topmost on

#
# setup spaces
#
for id in $(yabai -m query --spaces | jq '.[].index | select(. > 7)'); do
  yabai -m space --destroy $id
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 emacs
setup_space 2 console
setup_space 3 web
setup_space 4 code
setup_space 5 daw
setup_space 6 music
setup_space 7 messengers

# move some apps automatically to specific spaces
yabai -m rule --add app="^Emacs$" title!="^org-capture$" space=^1
yabai -m rule --add app="^Alacritty$" space=^2
yabai -m rule --add app="^Orion$" space=^3
yabai -m rule --add app="^Xcode$" space=^4
yabai -m rule --add app="^Dash$" space=^4
yabai -m rule --add app="^Live$" space=^5
yabai -m rule --add app="^Spotify$" space=^6

yabai -m rule --add app="^WhatsApp$" space=^7
yabai -m rule --add app="^Telegram$" space=^7
yabai -m rule --add app="^Slack$" space=^7
yabai -m rule --add app="^Discord$" space=^7
yabai -m rule --add app="^Skype$" space=^7
yabai -m rule --add app="^Element$" space=^7

# (tr)additional
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Preferences$" manage=off
yabai -m rule --add app="^Emacs$" title="^org-capture$" manage=off
