#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# config
# yabai -m config external_bar all:35:0
yabai -m config layout float

yabai -m config top_padding    8
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

yabai -m config window_placement first_child
yabai -m config auto_balance off
yabai -m config split_ratio 0.65
yabai -m config split_type vertical
yabai -m config window_shadow float

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config window_opacity        on

yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on

#
# setup spaces
#
for id in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy $id
done

function setup_space {
  local idx="$1"
  local name="$2"
  local layout="$3"
  local space=

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name" --layout "$layout"
}

setup_space 1 emacs bsp
yabai -m rule --add app="^Emacs$" space=^1

setup_space 2 terminal bsp
yabai -m rule --add app="^Alacritty$" space=^2

setup_space 3 wwwork bsp
yabai -m rule --add app="^Firefox$" space=^3

setup_space 4 comm float
yabai -m rule --add app="^(Telegram|Mattermost|Notability|WhatsApp|Discord|Messages)$" space=^4

setup_space 5 web bsp
yabai -m rule --add app="^Safari$" space=^5

setup_space 6 freeapp float

yabai -m rule --add app="^(Finder|Music|Podcasts|TV|VLC|System Settings|Preferences|Calendar|Dash|AppCleaner|Weather|Transmission|DeepL|Dropshare)$" manage=off

yabai -m signal --add event=window_created app="Emacs" action="~/.yabai/emacs-window-handler.sh"

echo "yabai configuration loaded.."
