# -*- mode: sh -*-

function addpath {
  export PATH="$PATH:$1"
}

export PATH=""

# kinda system paths
addpath "/bin"
addpath "/sbin"
addpath "/usr/bin"
addpath "/usr/sbin"
addpath "/usr/local/bin"
addpath "/usr/local/sbin"
addpath "/usr/X11/bin"

# custom tools
addpath "$HOME/.tools/bin"

# installed tools
addpath "$HOME/.luarocks/bin"
export GOPATH="$HOME/Documents/dev/golang/go"
addpath "$GOPATH/bin"
addpath "$HOME/.cargo/bin"
# addpath "$HOME/.cabal/bin"

# postgres
addpath "$HOMEBREW_PREFIX/opt/postgresql@16/bin"
# llvm
addpath "$HOMEBREW_PREFIX/opt/llvm/bin"
# zig
addpath "$HOME/Documents/dev/zig/zig/build/stage3/bin"
addpath "$HOME/Documents/dev/zig/zls/zig-out/bin"
# rust
addpath "$HOMEBREW_PREFIX/opt/rustup/bin"
